### ISSUE TITLE
Bug: ciSCSIInitiator does not work when hostname is used

### ISSUE THREAD

**Issue by Zuldan** [PlagueHO/ciSCSI#5]
@PlagueHO , thank you for writing this resource. I'm trying to get it installed in our environment but have come across a few issues. 

If you define the TargetPortalAddress with a hostname. The check at line 790 fails.

$Connection.TargetAddress -ne $TargetPortalAddress

This is because  Get-IscsiConnection returns an IP address and Get-IscsiTargetPortal returns an IP

ConnectionIdentifier : ffffe000fe0e2020-0
InitiatorAddress     : 0.0.0.0
InitiatorPortNumber  : 1472
TargetAddress        : 192.168.0.5
TargetPortNumber     : 3260
PSComputerName       :

and Get-IscsiTargetPortal returns a hostname

InitiatorInstanceName  :
InitiatorPortalAddress :
IsDataDigest           : False
IsHeaderDigest         : False
TargetPortalAddress    : MyTargetPortalHostname
TargetPortalPortNumber : 3260
PSComputerName         :

**Comment by PlagueHO** [comment]
Hi @Zuldan - I'm glad they're getting some use :smile: Also good that you've found these issues as I'm hoping to get them into the MSFT community resources.

Ah! I just checked and in all my systems I'm using IP Addresses for the TargetPortalAddress - so that is probably why I haven't run into it before. That is a good catch.

What I should be able to do is check if the ```(Get-IScsciTargetPortal).TargetPortalAddress``` and if it is not an IP address I could use a ```Resolve-DNSName``` to get it back to the IP Address. It is a little bit annoying how the some cmdlets output IP Addresses even if you specify a Hostname.

**Comment by PlagueHO** [comment]
@Zuldan - I think I've fixed this, but I just want to make sure I have completely fixed it. Are you able to dump a copy of the verbose log from applying this config so that I can check the verbose messages are the same as I what I expect?

**Comment by Zuldan** [comment]
No problem but do you mean run your code as it is or will you be providing some new code to run?

**Comment by PlagueHO** [comment]
Actually, I don't think I'll need the logs - I was running into a problem replicating the issue because I was also setting the InitiatorPortalAddress to a Hostname- but then I realized you weren't setting an InitiatorPortalAddress. I also have a dedicated iSCSI network that doesn't have the hostname listed in DNS so I was getting errors creating the portal.

Let me do a bit more work on this and get a fix through now that I can replicate your issue .

**Comment by Zuldan** [comment]
Fantastic. I really appreciate you working on this so quickly. Once https://github.com/PlagueHO/ciSCSI/issues/6 is sorted as well I will hopefully be able to run the resource successfully for the first time.
